### Question : 

A study was conducted to investigate whether there is a relationship between gender and the preferred genre of music. A sample of 235 people was selected and the data collected to shown below. Test at a 5% level of significance whether there is a significant association between gender and music preference.


|        | Pop | Hip Hop | Classical | Rock |
|--------|-----|----------|------------|------|
| Male   | 40  | 45       | 25         | 10   |
| Female | 35  | 30       | 20         | 30   |


### Answer : 

In [3]:
from scipy.stats import chi2
import numpy as np

In [1]:
alpha = 0.05
# degree_of_freedom = (row - 1) * (col - 1)
df = (2 - 1) * (4 - 1)
df

3

In [4]:
cv = chi2.ppf(1 - 0.05, df=df)
cv

np.float64(7.814727903251179)

In [5]:
row1 = np.array([40,45,25,10])
row2 = np.array([35,30,20,30])

In [11]:
sum_r1 = np.sum(row1)
sum_r2 = np.sum(row2)
sum_row = np.array([sum_r1, sum_r2])
sum_row

array([120, 115])

In [7]:
sum_col = row1 + row2
sum_col

array([75, 75, 45, 40])

In [14]:
exp = []
for i in sum_row:
    for j in sum_col:
        value = (i * j) / 235
        exp.append(value)


exp # expected value

[np.float64(38.297872340425535),
 np.float64(38.297872340425535),
 np.float64(22.97872340425532),
 np.float64(20.425531914893618),
 np.float64(36.702127659574465),
 np.float64(36.702127659574465),
 np.float64(22.02127659574468),
 np.float64(19.574468085106382)]

In [15]:
obv = np.array([40,45,25,10,35,30,20,30])
obv # observation value

array([40, 45, 25, 10, 35, 30, 20, 30])

In [18]:
chi_calc = np.sum(np.square(obv - exp) / exp)
chi_calc 

np.float64(13.788747987117553)

In [20]:
if chi_calc < cv :
    print("Ho is fair")
else:
    print("h1 is right , there are significant associatin between genders")

h1 is right , there are significant associatin between genders
